### ISSUE TITLE
Research REACT, etc. (For Herbie)

### ISSUE THREAD

**Issue by TheHerbenator** [EECE3093C/team-project-weather#14]
No experience with languages we're using, so I need to learn how in order to be an effective team member

```[tasklist]
### Tasks
- [x] modules on js basics
- [x] modules on REACT basics
- [x] Mentoring from Kai
```
